- name: Setup a catalogue component
  hosts: all
  become: yes
  vars:
    component: catalogue
  tasks:
    - name: load nodejs
















echo -e "${color} Configure nodejs repos ${nocolor}"
curl -sL https://rpm.nodesource.com/setup_lts.x | bash   &>>$log_file
stat_check $?
echo -e "${color} Install nodejs ${nocolor}"

yum install nodejs -y  &>>$log_file
stat_check $?
app_presetup

echo -e "${color} Install nodejs dependencies ${nocolor}"
npm install  &>>$log_file
stat_check $?
systemd_setup

echo -e "${color}  copy mongodb repo file ${nocolor}"
cp /root/RoboshopShellProject/mongodb.repo /etc/yum.repos.d/mongodb.repo  &>>$log_file
stat_check $?
echo -e "${color}  Install Mongodb client ${nocolor}"
yum install mongodb-org-shell -y  &>>$log_file
stat_check $?
echo -e "${color} Load schema ${nocolor}"
mongo --host mongodb-dev.ankadevopsb73.store <${app_path}/schema/$component.js  &>>$log_file
stat_check $?