- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: load app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Download maven dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml