- name: configuring nodejs Repos
  ansible.builtin.shell: curl curl -sL https://rpm.nodesource.com/setup_lts.x | bash
- name: Install nodejs

  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: load app presetup
  ansible.builtin.import_role:
    file: app_presetup.yml

- name: Change the working directory to somedir/ before executing the command
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_task:
    file: systemd_setup.yml